Draft Pull Request for Author Toolkit
bjones1/aata pull request #1
Opened 2023-04-21 19:00 UTC by jbrock1999h

This pull request adds codespace container files that will create the platform that authors use to easily edit their textbooks. The end goal is to have a button within the published textbook that links directly back to this codespace, allowing the textbook to be quickly and easily edited. So far, we have a codespace set up, but we do not yet have it as user friendly as we want it to be because it requires more git CLI manipulation than we want to get started.

This is an assignment for Josh Harvey and Daniel Short.

2023-04-21 19:39 UTC, bjones1 requested changes

2023-04-21 19:39 UTC, bjones1 commented on .devcontainer/devcontainer-20230420-004357.json
Remove this file from the commit -- it was auto-edited, so we no longer care about this stuff.

2023-04-21 19:39 UTC, bjones1 commented on .gitignore-20230420-004357
Remove this file also.

2023-04-21 19:39 UTC, bjones1 commented on project-20230420-004357.ptx
Remove...

2023-04-22 00:03 UTC, jbrock1999h reviewed
The requested files have been removed from the pull request

2023-04-25 19:29 UTC, bjones1 reviewed
Here are fixes/updates for your next PR; this is fine for the draft PR.

2023-04-25 19:29 UTC, bjones1 commented on .devcontainer/postStartCommand.sh
> +xdg-open http://localhost:8000-.preview.app.github.dev
I don't understand how this command (open a specific URL) relates to the previous comment (which says this command won't run?).

2023-04-25 19:29 UTC, bjones1 commented on .devcontainer/postCreateCommand.sh
> +# For the Digital System Design book...
You can remove all this.

2023-04-25 19:29 UTC, bjones1 commented on .devcontainer/docker-build.sh
> +#apt install -y xdg-utils
You seem to run this later, so uncomment it? (But I don't understand why running it is necessary...)

2023-04-25 19:29 UTC, bjones1 commented on .devcontainer/postStartCommand.sh
> +#pretext build
The pretext generate and pretext build should happen in the Docker container build, not here.

2023-04-25 19:29 UTC, merged